### ISSUE TITLE
Rails 4 log messages appear 2x

### ISSUE THREAD

**Issue by gkop** [heroku/rails_stdout_logging#1]
This is a brand new rails 4 rc2 app with the tweaks needed to run on heroku - https://github.com/gkop/heroku-rails-4-duplicate-logs .

Deploy to heroku, tail the logs, hit the / path, and you will see _2_ log messages (404) -- http://pastie.org/8053185 .

Heroku staff - I have deployed the app for you - http://heroku-rails-4-duplicate-logs.herokuapp.com/

**Comment by seanahrens** [comment]
For anyone who stumbles upon this issue from google, make sure that what's actually happening to you is not that your app is actually making duplicate REQUESTS as mine was. See http://stackoverflow.com/questions/3266020/rails-app-logging-duplicate-requests/28299100#28299100

**Comment by joallard** [comment]
Got this on 4.2, adding `group: :production`

**Comment by raldred** [comment]
Same, looks like this issue is back in 4.2.
Brand new 4.2.4 app today and I have double logging.

**Comment by schneems** [comment]
Open a new issue and give me an example app that reproduces the problem please
