### ISSUE TITLE
rails 4 support?

### ISSUE THREAD

**Issue by riffraff** [heroku/rails_stdout_logging#12]
this gem is mentioned in the rails_12factor docs in the "rails 4 section" but init.rb doesn't seem to do anything with rails v4

**Comment by dmathieu** [comment]
Init.rb is executed only when using this as a plugin. Rails4 dropped the support for plugins in favor of gems and engines.
We have several internal apps using this gem on rails 4 which work properly. Are you seeing a specific issue when adding the gem to your dependencies?

**Comment by riffraff** [comment]
thanks for the quick reply, the issue I had was that nothing was being logged to STDOUT. I has since moved to just setting logger to `Logger.new(STDOUT)` in my env so I am not sure this still happens or what might have caused it, I just happened to notice that line again today and thought I'd quickly check the code, which led me to submit the issue 

Might have been related to setting the log_level to something other than the default or interaction with some other gem, so I think you can close this issue and I'll create a new one if I can replicate the problem and isolate it. 

Thanks!

**Comment by schneems** [comment]
The most common problem is people putting this in their "production" group but running on a "staging" app environment.
