### ISSUE TITLE
Rails logger silence is not available

### ISSUE THREAD

**Issue by carlosantoniodasilva** [heroku/rails_stdout_logging#14]
We've hit an issue in production trying to use the Rails silence method on the logger:

```ruby
Rails.logger.silence { do_work }
```

This works fine with the [normal Rails logger because it includes the `LoggerSilence` module](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/logger.rb#L7), which provides [the `silence` method](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/logger_silence.rb#L12).

However, the heroku logger provided by this gem does not, which means the `silence` call ends up being the one available through the [Kernel extension that Rails adds](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/core_ext/kernel/reporting.rb#L108) (which is deprecated btw), and turns into an `ArgumentError`:

```ruby
#<ArgumentError: wrong number of arguments (0 for 1)>.

...gems/activesupport-4.2.1/lib/active_support/core_ext/kernel/reporting.rb:88:in `capture'
```

For now I've fixed this locally by including the `LoggerSilence` into the logger's singleton class when activating the stdout logging (since [it needs to be included](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/logger_silence.rb#L6) to have everything properly set up), and I'm wondering if this is something we can fix up in the gem itself, either by doing the same include:

```ruby
logger.singleton_class.include(LoggerSilence) if defined?(LoggerSilence)
```

Or by having a specific logger class for the gem, like: 

```ruby
  class StdoutLogger < ::Logger
    include ::LoggerSilence if defined?(::LoggerSilence)
  end
```

I think I prefer the second approach. Thoughts?

**Comment by schneems** [comment]
Seems bad. Thanks for the report :heart: I like the second approach better. Do you have time for a PR with test sometime this week.

**Comment by carlosantoniodasilva** [comment]
Yeah I'll work on it and send a PR later this week, just wanted to confirm the issue and the best approach, thanks :+1:.
