### ISSUE TITLE
`rails_stdout_logging`, `activerecord-session_store`, `#silence`, and thread-safety.

### ISSUE THREAD

**Issue by BrentWheeldon** [heroku/rails_stdout_logging#17]
Hi there,

After upgrading from `0.0.3` to `0.0.4` of `rails_stdout_logging` we starting noticing that after some point (usually about 30 minutes, but varying) our web dynos would stop logging almost completely. Messages with a severity of `:error` or higher still appeared in the logs, but nothing else. Our log level is set to `:info`.

We noticed that #15 started mixing `LoggerSilence` into the logger. I remember that when we introduced `activerecord-session_store` we had similar issues with logs (in that case we noticed it in tests - the test output would just stop) because of `logger.silence` calls. Looking at the code in `activerecord-session_store`, it is explicitly handling thread safety, whereas `activesupport`'s `LoggerSilence` looks to be susceptible to thread-safety problems.

For the time being we've locked to `0.0.3`, but I thought I'd just document this here in case anyone is playing along at home. It looks like there's an outstanding PR to rails ([here](https://github.com/rails/rails/pull/20507)) that should solve this once and for all.

Can anyone think of making the changes introduced in #15 opt-out-able?

Thanks!

**Comment by bartoszkopinski** [comment]
+1

**Comment by schneems** [comment]
Can we fix the bug in ActiveSupport?

**Comment by BrentWheeldon** [comment]
@schneems There's an open [PR](https://github.com/rails/rails/pull/20507) to fix it ActiveSupport that looks like it's getting close to being merged.

**Comment by schneems** [comment]
https://github.com/rails/rails/pull/20507 made things way worse and broke backwards compat I have an open issue https://github.com/rails/rails/issues/24263 we have a fix coming in https://github.com/heroku/rails_stdout_logging/pull/25 and are working to fix it in Rails proper.
