### ISSUE TITLE
Rails 2 compatibility

### ISSUE THREAD

**Issue by tagliala** [heroku/rails_stdout_logging#26]
As per README.md, rails_stdout_logging:

> Supports:
* Rails 3
* Rails 4

but there are still Rails 2 related files and code:
* https://github.com/heroku/rails_stdout_logging/blob/master/lib/rails_stdout_logging/rails2.rb
* https://github.com/heroku/rails_stdout_logging/blob/master/init.rb#L3

Is this still required?

**Comment by schneems** [comment]
I couldn't get the test app to work with all 3 versions of Rails so Rails2 should still work, but isn't officially supported in that if it suddenly breaks then who knows. This gem is mostly meant for Heroku users, and if you deploy a Rails2 app then we auto inject a plugin for you so you don't need it, however if you're on the Rails upgrade path I still want it to work so you can put it in your Gemfile today and have it work.

It's not been a maintenance problem to date, so I don't have a problem keeping those files in for now.

**Comment by tagliala** [comment]
Ok, thanks!
