### ISSUE TITLE
Migrating to Rails 5 notice does not include STDOUT.sync = true 

### ISSUE THREAD

**Issue by janraasch** [heroku/rails_stdout_logging#31]
Hi there, we recently switched to rails 5 and had some problems with stuff not showing up in our logs on heroku. Is there a specific reason why

```
STDOUT.sync = true
```

is not part of the `Migrating to Rails 5`-section on the README?

On the docs (https://devcenter.heroku.com/articles/logging#writing-to-your-log) it says

> To take advantage of the real-time logging, you may need to disable any log buffering your application may be carrying out.

and it was part of this `gem`: https://github.com/heroku/rails_stdout_logging/blob/master/lib/rails_stdout_logging/rails.rb#L18.

Is there a specific reason for leaving it out on the README and this is not needed when using `rails v5`?

**Comment by schneems** [comment]
I don't need it for my app github.com/codetriage/codetriage to log fine on Heroku

I'm fine if you want to send me a PR to add it to the readme.

**Comment by janraasch** [comment]
Okay. I can do that for sure.

Just out of curiosity then, do you remember why this https://github.com/heroku/rails_stdout_logging/blob/master/lib/rails_stdout_logging/rails.rb#L18 line is part of this gem in the first place?

**Comment by schneems** [comment]
If that's not true then ruby will buffer the logging. This means that logging will use less system resources but they will not sho up right after a line is logged.

**Comment by janraasch** [comment]
Yeah sure, I know the meaning of it. I was wondering why it was part of this gem, since you just said that you do **not need** this for your app.
