### ISSUE TITLE
STDOUT logging loses severity levels when passed through Logplex

### ISSUE THREAD

**Issue by gareth** [heroku/rails_stdout_logging#34]
Firstly, I realise this repo is old and deprecated, I just couldn't find a better place to raise this issue. Please point me somewhere else or tell me it's too unrelated if necessary.

One of the problems with Rails logging into Logplex via STDOUT is that the log levels are flattened, at best identifiable by text tags in the message. This is understandable, as simple IO streams just don't have the ability to tag different lines with different severities (they don't even have the concept of "lines" really)

Specifically, on the Heroku platform, all STDOUT is fed to Logplex as priority 190 (syslog facility/severity: `local7/information`). This reduces the effectiveness of using Logplex's syslog drains in addons like Papertrail, which otherwise have the ability to [filter messages by incoming severity](https://help.papertrailapp.com/kb/how-it-works/search-syntax#attributes).

![Papertrail's interface, showing a syslog severity filter being able to identify lines tagged by Heroku Postgres](https://user-images.githubusercontent.com/4975/71903339-c4b1e800-315b-11ea-8914-5d6fb6091057.png)

I'm listing this as an issue with the concept of an STDOUT logger because it feels like it should be (conceptually) possible to use syslog as an input to Logplex in the same way as e.g. Heroku Postgres appears to do in the screenshot above (it's definitely logging at different severities). A class like stdlib's [`Syslog::Logger`](https://ruby-doc.org/stdlib-2.6.1/libdoc/syslog/rdoc/Syslog/Logger.html) feels like it should in theory be able to integrate with Logplex in the same way that Postgres already does, unless there's something about the dyno architecture that makes that impossible.

I realise that in practice this isn't possible to configure on Heroku at the moment, but am I even right in theory?

**Comment by schneems** [comment]
> I'm listing this as an issue with the concept of an STDOUT logger because it feels like it should be (conceptually) possible to use syslog as an input to Logplex

Open a support ticket with Heroku. We can route that feedback to our logging team. Thats probably the best way to get this feedback to the place you want.

The way most people do it is to include the string in their output:

```
2020-01-13T18:13:04.628859+00:00 app[web.1]: I, [2020-01-13T18:13:04.628727 #7520]  INFO -- : source=rack-timeout id=5f8d8ff7-ec15-4c4c-94af-3e571bb0d45d wait=21ms timeout=15000ms state=ready
2020-01-13T18:13:04.629532+00:00 app[web.1]: D, [2020-01-13T18:13:04.629443 #7520] DEBUG -- : source=rack-timeout id=5f8d8ff7-ec15-4c4c-94af-3e571bb0d45d wait=21ms timeout=15000ms service=1ms state=active
```

Then after the fact you can search/group by the string.

Also you can set up logging by yourself and completely bypass Heroku's logplex if you wanted to, ship your own logs where-ever you want and however you want.

A support ticket is the best place for this if you still want to pursue it though. https://help.heroku.com search for "logplex" and open a ticket.
