### ISSUE TITLE
log ends up in rspec output

### ISSUE THREAD

**Issue by jjb** [heroku/rails_stdout_logging#6]
after installing 0.0.2, some logs are ending up in my rspec output, when doing controller tests.

let me know if you want more info, or if this is an rspec problem.

**Comment by pedro** [comment]
Ran into this too; fixed by adding to `config/environments/test.rb`:

```
config.log_level = :error
```

I have the `rails_stdout_logging` gem set on the default group of my Gemfile because I want dev/staging processes to log to stdout too.

**Comment by schneems** [comment]
you could also

```ruby
gem "rails_12factor", groups: [:production, :development]
```
